### ISSUE TITLE
Unlock the ability to over consume

### ISSUE THREAD

**Issue by erdnaxeli** [FreddecGames/ngsc#1]
Hi,

I just move over from the v1 version of this game, and first I want to thank you for the good job you did on it :+1: 

I noticed some changes that bothers me: we can't over consume anymore. The "build" button will stay inactive if building machine woud lead to a negative production of ressource. The same goes for destructing a machine.

I would like to have this behavior back. I use it a lot, when I know I have big storage and I can afford to have a negative production for some minutes while I accumulate ressources to build something else to have a positive production again.

Thanks :)

**Comment by FreddecGames** [comment]
Fixed with v2.4.0
